# Generated by Django 5.2.7 on 2025-10-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('numero_train', models.CharField()),
                ('carte_transport', models.CharField(default=False)),
                ('date_reservation', models.DateField()),
                ('nombre_personnes', models.IntegerField()),
            ],
        ),
    ]
